repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
        args: [--config, pyproject.toml, --fix, .]
      - id: ruff-format
        args: [--config, pyproject.toml, .]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml, .]
        language: system
        pass_filenames: false
