repos:
-   repo: local
    hooks:
    -   id: format
        name: format
        entry: ./shell/format.sh
        language: system

    -   id: lint
        name: lint
        entry: ./shell/lint.sh
        language: system
